/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedMyDayRouteImport } from './routes/_authenticated/my-day'
import { Route as AuthenticatedMyProjectsRouteImport } from './routes/_authenticated/my-projects'
import { Route as AuthenticatedOfficeLocationsRouteImport } from './routes/_authenticated/office-locations'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated/org'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedRosterImportRouteImport } from './routes/_authenticated/roster-import'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedWorkforceIndexRouteImport } from './routes/_authenticated/workforce/index'
import { Route as AuthenticatedWorkforcePersonIdRouteImport } from './routes/_authenticated/workforce/$personId'
import { Route as ApiPublicHooksDispatchInvitationsRouteImport } from './routes/api/public/hooks/dispatch-invitations'
import { Route as ApiPublicHooksRunAutomationRouteImport } from './routes/api/public/hooks/run-automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyDayRoute = AuthenticatedMyDayRouteImport.update({
  id: '/my-day',
  path: '/my-day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProjectsRoute = AuthenticatedMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficeLocationsRoute =
  AuthenticatedOfficeLocationsRouteImport.update({
    id: '/office-locations',
    path: '/office-locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterImportRoute =
  AuthenticatedRosterImportRouteImport.update({
    id: '/roster-import',
    path: '/roster-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkforceIndexRoute =
  AuthenticatedWorkforceIndexRouteImport.update({
    id: '/workforce/',
    path: '/workforce/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkforcePersonIdRoute =
  AuthenticatedWorkforcePersonIdRouteImport.update({
    id: '/workforce/$personId',
    path: '/workforce/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksDispatchInvitationsRoute =
  ApiPublicHooksDispatchInvitationsRouteImport.update({
    id: '/api/public/hooks/dispatch-invitations',
    path: '/api/public/hooks/dispatch-invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunAutomationRoute =
  ApiPublicHooksRunAutomationRouteImport.update({
    id: '/api/public/hooks/run-automation',
    path: '/api/public/hooks/run-automation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/my-day': typeof AuthenticatedMyDayRoute
  '/my-projects': typeof AuthenticatedMyProjectsRoute
  '/office-locations': typeof AuthenticatedOfficeLocationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/org': typeof AuthenticatedOrgRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/roster-import': typeof AuthenticatedRosterImportRoute
  '/team': typeof AuthenticatedTeamRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/workforce/$personId': typeof AuthenticatedWorkforcePersonIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/workforce/': typeof AuthenticatedWorkforceIndexRoute
  '/api/public/hooks/dispatch-invitations': typeof ApiPublicHooksDispatchInvitationsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/my-day': typeof AuthenticatedMyDayRoute
  '/my-projects': typeof AuthenticatedMyProjectsRoute
  '/office-locations': typeof AuthenticatedOfficeLocationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/org': typeof AuthenticatedOrgRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/roster-import': typeof AuthenticatedRosterImportRoute
  '/team': typeof AuthenticatedTeamRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/workforce/$personId': typeof AuthenticatedWorkforcePersonIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/workforce': typeof AuthenticatedWorkforceIndexRoute
  '/api/public/hooks/dispatch-invitations': typeof ApiPublicHooksDispatchInvitationsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/my-day': typeof AuthenticatedMyDayRoute
  '/_authenticated/my-projects': typeof AuthenticatedMyProjectsRoute
  '/_authenticated/office-locations': typeof AuthenticatedOfficeLocationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/roster-import': typeof AuthenticatedRosterImportRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/workforce/$personId': typeof AuthenticatedWorkforcePersonIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/workforce/': typeof AuthenticatedWorkforceIndexRoute
  '/api/public/hooks/dispatch-invitations': typeof ApiPublicHooksDispatchInvitationsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automation'
    | '/dashboard'
    | '/import'
    | '/invitations'
    | '/my-day'
    | '/my-projects'
    | '/office-locations'
    | '/onboarding'
    | '/org'
    | '/reports'
    | '/requests'
    | '/reviews'
    | '/roster-import'
    | '/team'
    | '/projects/$projectId'
    | '/workforce/$personId'
    | '/projects/'
    | '/workforce/'
    | '/api/public/hooks/dispatch-invitations'
    | '/api/public/hooks/run-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automation'
    | '/dashboard'
    | '/import'
    | '/invitations'
    | '/my-day'
    | '/my-projects'
    | '/office-locations'
    | '/onboarding'
    | '/org'
    | '/reports'
    | '/requests'
    | '/reviews'
    | '/roster-import'
    | '/team'
    | '/projects/$projectId'
    | '/workforce/$personId'
    | '/projects'
    | '/workforce'
    | '/api/public/hooks/dispatch-invitations'
    | '/api/public/hooks/run-automation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/automation'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/invitations'
    | '/_authenticated/my-day'
    | '/_authenticated/my-projects'
    | '/_authenticated/office-locations'
    | '/_authenticated/onboarding'
    | '/_authenticated/org'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/reviews'
    | '/_authenticated/roster-import'
    | '/_authenticated/team'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/workforce/$personId'
    | '/_authenticated/projects/'
    | '/_authenticated/workforce/'
    | '/api/public/hooks/dispatch-invitations'
    | '/api/public/hooks/run-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksDispatchInvitationsRoute: typeof ApiPublicHooksDispatchInvitationsRoute
  ApiPublicHooksRunAutomationRoute: typeof ApiPublicHooksRunAutomationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-day': {
      id: '/_authenticated/my-day'
      path: '/my-day'
      fullPath: '/my-day'
      preLoaderRoute: typeof AuthenticatedMyDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-projects': {
      id: '/_authenticated/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof AuthenticatedMyProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office-locations': {
      id: '/_authenticated/office-locations'
      path: '/office-locations'
      fullPath: '/office-locations'
      preLoaderRoute: typeof AuthenticatedOfficeLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster-import': {
      id: '/_authenticated/roster-import'
      path: '/roster-import'
      fullPath: '/roster-import'
      preLoaderRoute: typeof AuthenticatedRosterImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce/': {
      id: '/_authenticated/workforce/'
      path: '/workforce'
      fullPath: '/workforce/'
      preLoaderRoute: typeof AuthenticatedWorkforceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce/$personId': {
      id: '/_authenticated/workforce/$personId'
      path: '/workforce/$personId'
      fullPath: '/workforce/$personId'
      preLoaderRoute: typeof AuthenticatedWorkforcePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/dispatch-invitations': {
      id: '/api/public/hooks/dispatch-invitations'
      path: '/api/public/hooks/dispatch-invitations'
      fullPath: '/api/public/hooks/dispatch-invitations'
      preLoaderRoute: typeof ApiPublicHooksDispatchInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-automation': {
      id: '/api/public/hooks/run-automation'
      path: '/api/public/hooks/run-automation'
      fullPath: '/api/public/hooks/run-automation'
      preLoaderRoute: typeof ApiPublicHooksRunAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedMyDayRoute: typeof AuthenticatedMyDayRoute
  AuthenticatedMyProjectsRoute: typeof AuthenticatedMyProjectsRoute
  AuthenticatedOfficeLocationsRoute: typeof AuthenticatedOfficeLocationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedRosterImportRoute: typeof AuthenticatedRosterImportRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedWorkforcePersonIdRoute: typeof AuthenticatedWorkforcePersonIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedWorkforceIndexRoute: typeof AuthenticatedWorkforceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedMyDayRoute: AuthenticatedMyDayRoute,
  AuthenticatedMyProjectsRoute: AuthenticatedMyProjectsRoute,
  AuthenticatedOfficeLocationsRoute: AuthenticatedOfficeLocationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedRosterImportRoute: AuthenticatedRosterImportRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedWorkforcePersonIdRoute: AuthenticatedWorkforcePersonIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedWorkforceIndexRoute: AuthenticatedWorkforceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksDispatchInvitationsRoute:
    ApiPublicHooksDispatchInvitationsRoute,
  ApiPublicHooksRunAutomationRoute: ApiPublicHooksRunAutomationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
